import React, { useState, useEffect } from 'react';
import { Search, Filter, MoreHorizontal, Edit2, Trash2, UserPlus, MessageCircle } from 'lucide-react';
import { useToast } from '../contexts/ToastContext';
import { PatientModal } from '../components/PatientModal';
import { getWhatsAppLink } from '../lib/utils';

export function Patients() {
  const { addToast } = useToast();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [activeMenu, setActiveMenu] = useState<{ id: number | string, top: number, left: number } | null>(null);
  const [editingPatient, setEditingPatient] = useState<any>(null);
  const [patientsList, setPatientsList] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchPatients = async () => {
    try {
      const response = await fetch('/api/patients');
      const data = await response.json();
      setPatientsList(data);
    } catch (error) {
      console.error('Error fetching patients:', error);
      addToast('Erro ao carregar pacientes', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPatients();
  }, []);

  const handleDelete = async (id: number | string) => {
    try {
      await fetch(`/api/patients/${id}`, { method: 'DELETE' });
      setPatientsList(patientsList.filter(p => p.id !== id));
      addToast('Paciente excluído com sucesso', 'success');
      setActiveMenu(null);
    } catch (error) {
      console.error('Error deleting patient:', error);
      addToast('Erro ao excluir paciente', 'error');
    }
  };

  const handleEdit = (patient: any) => {
    setEditingPatient(patient);
    setIsModalOpen(true);
    setActiveMenu(null);
  };

  const handleSavePatient = async (patientData: any) => {
    try {
      if (editingPatient) {
        await fetch(`/api/patients/${patientData.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(patientData),
        });
        setPatientsList(patientsList.map(p => p.id === patientData.id ? patientData : p));
      } else {
        await fetch('/api/patients', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(patientData),
        });
        // Refresh list to get the new ID if generated by server, or just append
        fetchPatients();
      }
      setIsModalOpen(false);
      setEditingPatient(null);
    } catch (error) {
      console.error('Error saving patient:', error);
      addToast('Erro ao salvar paciente', 'error');
    }
  };

  const openNewPatientModal = () => {
    setEditingPatient(null);
    setIsModalOpen(true);
  };

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Pacientes</h1>
          <p className="text-slate-500 mt-1">Gerencie seus pacientes e históricos</p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={openNewPatientModal}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 transition-colors shadow-sm shadow-blue-200"
          >
            <UserPlus className="w-4 h-4" />
            Novo Paciente
          </button>
          <div className="relative">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input 
              type="text" 
              placeholder="Buscar paciente..." 
              className="pl-10 pr-4 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 w-64"
            />
          </div>
          <button className="p-2 border border-slate-200 rounded-lg hover:bg-slate-50 text-slate-600">
            <Filter className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-100 shadow-sm overflow-hidden">
        <table className="w-full text-left">
          <thead>
            <tr className="bg-slate-50/50 border-b border-slate-100">
              <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">Nome</th>
              <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">Plano</th>
              <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">Contato</th>
              <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">Última Visita</th>
              <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">Status</th>
              <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider text-right">Ações</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {patientsList.map((patient) => (
              <tr key={patient.id} className="hover:bg-slate-50/50 transition-colors">
                <td className="px-6 py-4">
                  <div className="font-medium text-slate-900">{patient.name}</div>
                  <div className="text-xs text-slate-500">{patient.email}</div>
                </td>
                <td className="px-6 py-4">
                  <span className="text-sm font-medium text-slate-600">{patient.plan}</span>
                </td>
                <td className="px-6 py-4 text-sm text-slate-600">
                  <div className="flex items-center gap-2">
                    {patient.phone}
                    <button 
                      onClick={() => {
                        const link = getWhatsAppLink(patient.phone, `Olá ${patient.name}, tudo bem?`);
                        window.open(link, '_blank');
                      }}
                      className="p-1 text-emerald-600 hover:bg-emerald-50 rounded transition-colors"
                      title="Conversar no WhatsApp"
                    >
                      <MessageCircle className="w-4 h-4" />
                    </button>
                  </div>
                </td>
                <td className="px-6 py-4 text-sm text-slate-600">{patient.lastVisit}</td>
                <td className="px-6 py-4">
                  <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                    patient.status === 'Ativo' ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-800'
                  }`}>
                    {patient.status}
                  </span>
                </td>
                <td className="px-6 py-4 text-right relative">
                  <button 
                    onClick={(e) => {
                      e.stopPropagation();
                      const rect = e.currentTarget.getBoundingClientRect();
                      setActiveMenu(activeMenu?.id === patient.id ? null : { 
                        id: patient.id, 
                        top: rect.bottom + window.scrollY, 
                        left: rect.left + window.scrollX - 100 // Adjust to align left
                      });
                    }}
                    className="text-slate-400 hover:text-slate-600 p-1 rounded-full hover:bg-slate-100 transition-colors"
                  >
                    <MoreHorizontal className="w-5 h-5" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {activeMenu && (
        <>
          <div 
            className="fixed inset-0 z-40" 
            onClick={() => setActiveMenu(null)}
          />
          <div 
            className="fixed z-50 w-32 bg-white rounded-lg shadow-lg border border-slate-100 py-1 animate-in fade-in zoom-in-95 duration-100"
            style={{ top: activeMenu.top, left: activeMenu.left }}
          >
            <button 
              onClick={() => {
                const patient = patientsList.find(p => p.id === activeMenu.id);
                if (patient) handleEdit(patient);
              }}
              className="w-full flex items-center gap-2 px-4 py-2 text-sm text-slate-600 hover:bg-slate-50 transition-colors"
            >
              <Edit2 className="w-3.5 h-3.5" />
              Editar
            </button>
            <button 
              onClick={() => handleDelete(activeMenu.id)}
              className="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50 transition-colors"
            >
              <Trash2 className="w-3.5 h-3.5" />
              Excluir
            </button>
          </div>
        </>
      )}

      <PatientModal 
        isOpen={isModalOpen} 
        onClose={() => {
          setIsModalOpen(false);
          setEditingPatient(null);
        }} 
        onSave={handleSavePatient}
        initialData={editingPatient}
      />
    </div>
  );
}
